name = input("enter your name:")
usn = input("enter your usn:")
section = input("enter your section:")
college = input("enter your college name:")
branch = input("enter your branch:")
print("name:",name)
print("usn:",usn)
print("section:",section)
print("college:",college)
print("branch:",branch)
